"""
ONES Spectrum-X Python SDK.

Public API:

    All 97 Fabric Manager API functions are re-exported here
    (create_tenant, get_all_fabrics, update_tenant, ...),
    mirroring ones_gfx.apis.

    ONESClient         - main entry point
    JWTAuth            - JWT-based authentication
    OperationMode      - sync / async-poll / async-webhook
    OperationStatus    - PENDING / RUNNING / SUCCESS / FAILURE
    ConfigStatus       - tenant configuration state enum
    UNLIMITED_GPUS     - sentinel value for max_gpus_allowed=-1

    Models:
        Fabric, Tenant, VNetInfo, Operation, NMXCPartition

    Exceptions:
        ONESError (base), AuthenticationError, BadRequestError,
        NotFoundError, ConflictError, ServerError, TransportError,
        OperationFailedError, APIError
"""

from ._version import __version__
from .auth import AuthBase, JWTAuth
from .client import Client, NotAuthenticatedError, ONESClient
from .enums import (
    UNLIMITED_GPUS,
    ConfigStatus,
    OperationMode,
    OperationStatus,
)
from .exceptions import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConfigurationFailedError,
    ConflictError,
    NotFoundError,
    ONESError,
    OperationFailedError,
    ServerError,
    TransportError,
)
from .models import Fabric, NMXCPartition, Operation, Tenant, VNetInfo
from .apis import (
    create_tenant,
    list_tenants,
    get_tenant,
    update_tenant,
    delete_tenant,
    get_operation,
    get_operation_webhook_status,
    add_fabric_data,
    edit_fabric_data,
    delete_fabric_data,
    get_all_fabrics,
    get_fabric_by_name,
    get_fabrics,
    update_fabric_status,
    get_fabric_devices,
    get_devices_by_layer,
    add_fabric_sim,
    get_all_fabric_sims,
    get_fabric_sim_by_name,
    delete_fabric_sim,
    update_fabric_sim_status,
    add_inventory_data,
    update_inventory_data,
    edit_inventory_data,
    get_all_inventory,
    get_inventory_by_fabric_name,
    get_fm_inventory,
    get_inventory_ports,
    get_inventory_hosts,
    inventory_sync,
    validate_ufm_creds,
    update_nmxc_domains,
    probe_nmxc_domains,
    get_nmxc_inventory,
    create_vpc_peering,
    delete_vpc_peering,
    modify_gpu_allocations,
    assign_gpu_ports,
    auto_allocate_gpus_to_tenants,
    get_all_gpus_list,
    get_gpus_by_host,
    get_gpu_tenant_mappings,
    get_gpu_allocation_history,
    get_available_servers,
    upload_day1_config,
    upload_ui_object,
    get_ui_object,
    get_last_orchestrated_intent_name,
    get_day1_config_status,
    get_intent_validation,
    get_intent_derivation_logs,
    get_upload_status,
    is_device_alive,
    add_device_facts,
    remove_device_facts,
    get_version,
    get_imgmgmt_status,
    upgrade_nos_image,
    enable_ztp_upgrade,
    reboot_request,
    backup_config,
    restore_config,
    configs_list_to_restore,
    fetch_device_backup_files,
    get_config_diff,
    replace_config,
    get_config,
    fill_bootstrap_config,
    trigger_bootstrap_config,
    get_bootstrap_info,
    get_all_bootstrap_batches,
    get_bootstrap_batch,
    get_device_bootstrap_stages,
    fill_rma_config,
    trigger_rma,
    get_rma_info,
    get_rma_status,
    upload_file,
    get_files,
    delete_file,
    update_role_info,
    get_log_level,
    set_log_level,
    get_status,
    start_streaming,
    stop_streaming,
    get_controller_version,
    get_controller_version_internal,
    netops_fabric,
    netops_device,
    add_host_tenant_data,
    delete_host_tenant_data,
    get_host_tenants_list,
    update_hosts,
    get_hosts_list,
    reset_nmxc_domain,
    factory_reset_nmxc_domain,
)

__all__ = [
    "__version__",
    "Client",
    "NotAuthenticatedError",
    "ONESClient",
    "AuthBase",
    "JWTAuth",
    "OperationMode",
    "OperationStatus",
    "ConfigStatus",
    "UNLIMITED_GPUS",
    "Fabric",
    "Tenant",
    "VNetInfo",
    "Operation",
    "NMXCPartition",
    "ONESError",
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "NotFoundError",
    "ConflictError",
    "ServerError",
    "TransportError",
    "OperationFailedError",
    "ConfigurationFailedError",
    "create_tenant",
    "list_tenants",
    "get_tenant",
    "update_tenant",
    "delete_tenant",
    "get_operation",
    "get_operation_webhook_status",
    "add_fabric_data",
    "edit_fabric_data",
    "delete_fabric_data",
    "get_all_fabrics",
    "get_fabric_by_name",
    "get_fabrics",
    "update_fabric_status",
    "get_fabric_devices",
    "get_devices_by_layer",
    "add_fabric_sim",
    "get_all_fabric_sims",
    "get_fabric_sim_by_name",
    "delete_fabric_sim",
    "update_fabric_sim_status",
    "add_inventory_data",
    "update_inventory_data",
    "edit_inventory_data",
    "get_all_inventory",
    "get_inventory_by_fabric_name",
    "get_fm_inventory",
    "get_inventory_ports",
    "get_inventory_hosts",
    "inventory_sync",
    "validate_ufm_creds",
    "update_nmxc_domains",
    "probe_nmxc_domains",
    "get_nmxc_inventory",
    "create_vpc_peering",
    "delete_vpc_peering",
    "modify_gpu_allocations",
    "assign_gpu_ports",
    "auto_allocate_gpus_to_tenants",
    "get_all_gpus_list",
    "get_gpus_by_host",
    "get_gpu_tenant_mappings",
    "get_gpu_allocation_history",
    "get_available_servers",
    "upload_day1_config",
    "upload_ui_object",
    "get_ui_object",
    "get_last_orchestrated_intent_name",
    "get_day1_config_status",
    "get_intent_validation",
    "get_intent_derivation_logs",
    "get_upload_status",
    "is_device_alive",
    "add_device_facts",
    "remove_device_facts",
    "get_version",
    "get_imgmgmt_status",
    "upgrade_nos_image",
    "enable_ztp_upgrade",
    "reboot_request",
    "backup_config",
    "restore_config",
    "configs_list_to_restore",
    "fetch_device_backup_files",
    "get_config_diff",
    "replace_config",
    "get_config",
    "fill_bootstrap_config",
    "trigger_bootstrap_config",
    "get_bootstrap_info",
    "get_all_bootstrap_batches",
    "get_bootstrap_batch",
    "get_device_bootstrap_stages",
    "fill_rma_config",
    "trigger_rma",
    "get_rma_info",
    "get_rma_status",
    "upload_file",
    "get_files",
    "delete_file",
    "update_role_info",
    "get_log_level",
    "set_log_level",
    "get_status",
    "start_streaming",
    "stop_streaming",
    "get_controller_version",
    "get_controller_version_internal",
    "netops_fabric",
    "netops_device",
    "add_host_tenant_data",
    "delete_host_tenant_data",
    "get_host_tenants_list",
    "update_hosts",
    "get_hosts_list",
    "reset_nmxc_domain",
    "factory_reset_nmxc_domain",
]
